FROM node:18-alpine

WORKDIR /app

# Install development dependencies
COPY package*.json ./
RUN npm install

# Expose the port the app runs on
EXPOSE 7001

# Command to run the application is specified in docker-compose
CMD ["npm", "run", "dev"]
